---
- hosts: digitalocean
  vars:
    do_token: "{{ lookup('env','DO_API_TOKEN') }}"
    droplet_name: hiddenservice  # Droplet name
    unique_name: yes             # Set to 'no' to create new droplets with the same name
  roles:
    - provision-server

- hosts: webservers
  remote_user: root
  roles:
    - base 
    - tor
    - webserver
    - finish