---
- hosts: digitalocean
  vars:
    do_token: "{{ lookup('env','DO_API_TOKEN') }}"
    droplets: 
    - hiddenservice
  roles:
    - provision-server

- hosts: webservers
  remote_user: root
  roles:
    - base 
    - tor
    - webserver
    - finish