---
- name: Add nginx repository key
  apt_key: 
    url: "http://nginx.org/keys/nginx_signing.key" 
    state: "present"

- name: Add nginx repository
  apt_repository: 
    repo: "deb http://nginx.org/packages/debian/ jessie nginx" 
    state: "present" 
    update_cache: "yes" 

- name: Install nginx
  apt:
    name: "nginx"
    state: latest

- name: Create webroot
  file: 
    path: "/var/www/html"
    state: directory

- name: Copy default index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: nginx configuration
  template:
    src: nginx_site.j2
    dest: /etc/nginx/conf.d/website.conf
    
- name: Disable default nginx site
  file: 
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Disable server tokens
  replace:
    dest: /etc/nginx/nginx.conf
    regexp: "# server_tokens off;"
    replace: "server_tokens off;"



#- name: Create dhparams
#  shell: "/usr/bin/openssl dhparam 4096 > /etc/ssl/certs/graffendk_params.pem"
#  args: 
#    creates: /etc/ssl/certs/graffendk_params.pem
